In [1]:
from tensorflow.keras.applications.resnet50 import ResNet50
from tensorflow.keras.preprocessing import image
from tensorflow.keras.applications.resnet50 import preprocess_input, decode_predictions
import numpy as np

In [2]:
model = ResNet50(weights='imagenet')

102967424/102967424 ━━━━━━━━━━━━━━━━━━━━ 6s 0us/step


## Image 1


In [3]:
img_path = '/content/miki.jpeg'
img = image.load_img(img_path, target_size=(224, 224))
x = image.img_to_array(img)
x = np.expand_dims(x, axis=0)
x = preprocess_input(x)

In [4]:
x

array([[[[ 7.8060997e+01,  4.0221001e+01,  2.3320000e+01],
         [ 8.5060997e+01,  4.5221001e+01,  2.8320000e+01],
         [ 9.2060997e+01,  5.0221001e+01,  3.4320000e+01],
         ...,
         [ 1.5006100e+02,  1.0522100e+02,  8.7320000e+01],
         [ 1.5006100e+02,  1.0522100e+02,  8.7320000e+01],
         [ 1.4906100e+02,  1.0422100e+02,  8.6320000e+01]],

        [[ 7.3060997e+01,  3.5221001e+01,  1.8320000e+01],
         [ 8.2060997e+01,  4.2221001e+01,  2.5320000e+01],
         [ 8.8060997e+01,  4.6221001e+01,  3.0320000e+01],
         ...,
         [ 1.4906100e+02,  1.0422100e+02,  8.6320000e+01],
         [ 1.4906100e+02,  1.0422100e+02,  8.6320000e+01],
         [ 1.4906100e+02,  1.0422100e+02,  8.6320000e+01]],

        [[ 7.0060997e+01,  3.1221001e+01,  1.7320000e+01],
         [ 8.0060997e+01,  3.9221001e+01,  2.5320000e+01],
         [ 8.7060997e+01,  4.5221001e+01,  3.1320000e+01],
         ...,
         [ 1.4706100e+02,  1.0222100e+02,  8.4320000e+01],
         [

In [5]:
preds = model.predict(x)
print('Predicted:', decode_predictions(preds, top=3)[0])

1/1 ━━━━━━━━━━━━━━━━━━━━ 6s 6s/step
35363/35363 ━━━━━━━━━━━━━━━━━━━━ 0s 1us/step
Predicted: [('n02123394', 'Persian_cat', np.float32(0.9843918)), ('n02127052', 'lynx', np.float32(0.0059775887)), ('n02123159', 'tiger_cat', np.float32(0.005369622))]


## Image 2

In [6]:
img_path = '/content/bulldog.jpg'
img = image.load_img(img_path, target_size=(224, 224))
x = image.img_to_array(img)
x = np.expand_dims(x, axis=0)
x = preprocess_input(x)

In [7]:
x

array([[[[ 98.061  ,  86.221  ,  77.32   ],
         [ 98.061  ,  86.221  ,  77.32   ],
         [ 98.061  ,  86.221  ,  77.32   ],
         ...,
         [113.061  , 103.221  ,  94.32   ],
         [112.061  , 102.221  ,  93.32   ],
         [112.061  , 102.221  ,  93.32   ]],

        [[ 98.061  ,  86.221  ,  77.32   ],
         [ 98.061  ,  86.221  ,  77.32   ],
         [ 98.061  ,  86.221  ,  77.32   ],
         ...,
         [116.061  , 106.221  ,  97.32   ],
         [116.061  , 106.221  ,  97.32   ],
         [115.061  , 105.221  ,  96.32   ]],

        [[ 98.061  ,  86.221  ,  77.32   ],
         [ 98.061  ,  86.221  ,  77.32   ],
         [ 98.061  ,  86.221  ,  77.32   ],
         ...,
         [117.061  , 107.221  ,  98.32   ],
         [117.061  , 107.221  ,  98.32   ],
         [116.061  , 106.221  ,  97.32   ]],

        ...,

        [[114.061  , 101.221  ,  94.32   ],
         [117.061  , 104.221  ,  97.32   ],
         [120.061  , 107.221  , 100.32   ],
         ...,


In [8]:
preds = model.predict(x)
print('Predicted:', decode_predictions(preds, top=3)[0])

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 43ms/step
Predicted: [('n02108422', 'bull_mastiff', np.float32(0.34965074)), ('n02108915', 'French_bulldog', np.float32(0.26346475)), ('n02108089', 'boxer', np.float32(0.07222487))]


## Image 3

In [9]:
img_path = '/content/car.jpg'
img = image.load_img(img_path, target_size=(224, 224))
x = image.img_to_array(img)
x = np.expand_dims(x, axis=0)
x = preprocess_input(x)

In [10]:
x

array([[[[ 87.061     ,  90.221     ,  96.32      ],
         [ 87.061     ,  90.221     ,  96.32      ],
         [ 87.061     ,  90.221     ,  96.32      ],
         ...,
         [ 56.060997  ,  51.221     ,  44.32      ],
         [ 58.060997  ,  53.221     ,  46.32      ],
         [ 58.060997  ,  53.221     ,  46.32      ]],

        [[ 88.061     ,  91.221     ,  97.32      ],
         [ 88.061     ,  91.221     ,  97.32      ],
         [ 88.061     ,  91.221     ,  97.32      ],
         ...,
         [ 56.060997  ,  51.221     ,  44.32      ],
         [ 58.060997  ,  53.221     ,  46.32      ],
         [ 58.060997  ,  53.221     ,  46.32      ]],

        [[ 89.061     ,  92.221     ,  98.32      ],
         [ 89.061     ,  92.221     ,  98.32      ],
         [ 89.061     ,  92.221     ,  98.32      ],
         ...,
         [ 56.060997  ,  51.221     ,  44.32      ],
         [ 58.060997  ,  53.221     ,  46.32      ],
         [ 58.060997  ,  53.221     ,  46.32      ]],

In [11]:
preds = model.predict(x)
print('Predicted:', decode_predictions(preds, top=3)[0])

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 43ms/step
Predicted: [('n04285008', 'sports_car', np.float32(0.528928)), ('n04037443', 'racer', np.float32(0.46694115)), ('n03100240', 'convertible', np.float32(0.0015967176))]
